### PR TITLE
fix: do not encode file names of dynamic routes

### LINKED ISSUE #167: File names of dynamic routes in the build output should not be URI-encoded
[troubleshooting section]: https://iles-docs.netlify.app/faqs/troubleshooting

- [x] I have read the __[troubleshooting section]__ before opening an issue.
- [x] I have tried upgrading `iles` and `vite`.

### Description 📖

The file names of dynamic routes are URI-encoded in the build output which breaks the links.

### Reproduction 🐞

https://github.com/ouuan/iles-uri-encoding-broken-link-demo

The build outputs:

```
dist
├── foo%20bar.html
├── foobar.html
├── index.html
└── static foo bar.html
```

Here `foo%20bar` is generated from a dynamic route, and `static foo bar` is a static route.

`/foo bar` breaks, and we need to access it via `/foo%2520bar`.

### PR DESCRIPTION
**Pull request by ouuan**
### Description 📖

This fixes #167.

### Background 📜

#167

### The Fix 🔨

Decode the resolved path in the file name, but keep `%2F` (`/`) encoded.

### CODE REVIEW

**Comment by ElMassimo** [comment]
Thanks @ouuan! Would you rebase so that the CI runs all tests?

File: packages/iles/src/node/build/utils.ts [hunk 1]
```diff
@@ -40,7 +40,8 @@ export function flattenPath (path: string) {
 // Paths ending with '/' are represented with index.html files.
 export function pathToFilename (path: string, ext = '') {
   if (path.endsWith(ext)) ext = ''
-  return `${(path.endsWith('/') ? `${path}index` : path).replace(/^\//g, '')}${ext}`
+  const decodedPath = path.split('%2F').map(decodeURIComponent).join('%2F')
+  return `${(decodedPath.endsWith('/') ? `${decodedPath}index` : decodedPath).replace(/^\//g, '')}${ext}`
```
Comment (ElMassimo) [inline packages/iles/src/node/build/utils.ts:44]: I'm not sure about slashes being encoded (`%2F`), as it would mean this check never adds `index` as the filename (which it does).

`vue-router` probably doesn't encode slashes, it should only be encoding certain path segments.

Comment (ouuan) [reply packages/iles/src/node/build/utils.ts:44]: I guess the slashes as delimiters are not encoded, but slashes as path params are encoded? Not very sure though, maybe some tests are needed.

Comment (ElMassimo) [reply packages/iles/src/node/build/utils.ts:44]: That makes sense, so I think we should do `split('/').map(decodeURIComponent).join('/')`, which should handle slashes in the dynamic paths as well.

Comment (ouuan) [reply packages/iles/src/node/build/utils.ts:44]: After some testing, now I think it's just fine to do `decodeURIComponent(path)` without special handling of slashes. But isn't `split('/').map(decodeURIComponent).join('/')` the same as `decodeURIComponent`?

**Comment by ElMassimo** [comment]
Excellent, thanks!

**Comment by ouuan** [comment]
May I request a release for this? Now I'm having broken links in production.

**Comment by ElMassimo** [comment]
Hi @ouuan, this was released in `0.8.2`.
